### ISSUE TITLE
Running Behind a Reverse Proxy

### ISSUE THREAD

**Issue by nikeee** [mkopylec/recaptcha-spring-boot-starter#11]
We are running our service behind a reverse proxy. Therefore, `request.getRemoteAddr()` will return the IP address of the reverse proxy, not the client that solves the captcha.

The reverse proxy is configured to set the header `X-Forwarded-For` (and `X-Real-IP`).

This library uses `request.getRemoteAddr()` in these locations:
https://github.com/mkopylec/recaptcha-spring-boot-starter/blob/a4b13148998b039daa46bd1f806e80a149ee527c/src/main/java/com/github/mkopylec/recaptcha/security/RecaptchaAuthenticationFilter.java#L52
https://github.com/mkopylec/recaptcha-spring-boot-starter/blob/a4b13148998b039daa46bd1f806e80a149ee527c/src/main/java/com/github/mkopylec/recaptcha/validation/RecaptchaValidator.java#L28

To make this work with our setup, we would need to change this into `request.getHeader("X-Forwarded-For")`. Is there a recommended way for doing this? Or is this currently not supported?

**Comment by mkopylec** [comment]
I think this is the recomended way but it is not implemented in the library right now. Ill add it to the library.

**Comment by notableTieView** [comment]
I added a solution using two new settings (specifying that there is a proxy, and specifying the header in case X-Forwarded-For is not used). 
Thanks for the great library!

**Comment by mkopylec** [comment]
Fixed in 2.3.0
