### ISSUE TITLE
InMemoryLoginFailuresManager is not performing threadsafe counter increment

### ISSUE THREAD

**Issue by ksmith97** [mkopylec/recaptcha-spring-boot-starter#14]
The mechanism used in InMemoryLoginFailuresManager to track failure attempts is not using a thread safe mechanism to perform its increment of the login failures.  Ideally the retrieval of the previous value and the increment should be done as a single atomic action. In this scenario that would mean using ConcurrentHashMap.compute.

The impact seems minor because at worst a few more login failures might be allowed.

**Comment by mkopylec** [comment]
Fixed in 2.3.0
