### ISSUE TITLE
Documentation for configuration keys

### ISSUE THREAD

**Issue by snicoll** [mkopylec/recaptcha-spring-boot-starter#2]
Could you please add documentation for the configuration keys that you define? This would provide a better user experience in the IDE

>  The Javadoc for field values within configuration classes will be used to populate the description attribute.

Check [ServerProperties](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java) for an example.

**Comment by mkopylec** [comment]
Done
