### ISSUE TITLE
Include script async/defer

### ISSUE THREAD

**Issue by shakuzen** [mkopylec/recaptcha-spring-boot-starter#3]
Very much a nit-pick and of course it will run properly either way, but I noticed on [Google's documentation](https://developers.google.com/recaptcha/docs/display) that they use `async defer` with the `script` tag in all of their examples, but the README here does not. Would it be best to align the README with the official documentation's sample code? Or was it a conscious decision to not include `async defer`? If it does get updated in the README, it would be good to update the samples also.

**Comment by mkopylec** [comment]
You are right, I missed those attributes somehow. I'll fix it soon. Thanks!

**Comment by mkopylec** [comment]
Done
