### ISSUE TITLE
[notabug] Hello!

### ISSUE THREAD

**Issue by aol-nnov** [mkopylec/recaptcha-spring-boot-starter#5]
Just chiming in to say thank you for this nifty contribution! :v:

**Comment by mkopylec** [comment]
Thank you! 
Star it if you like it :-)

**Comment by aol-nnov** [comment]
Star is a star, but a record in the log makes its own sense :) (I've starred it anyway :) )

**Comment by mkopylec** [comment]
I hope the starter will serve you well. Thanks again!
