### ISSUE TITLE
Able to login without validating reCaptcha

### ISSUE THREAD

**Issue by manojsharma20** [mkopylec/recaptcha-spring-boot-starter#8]
Hi,

First of all thank for creating such a good plugin for spring boot based project.

Now my issue:

I have configure your recaptcha example and working fine, but the issue is i am able to login into the system without verify recaptcha.

I don't know what i am missing. Please help me to solve this issue.

Code form Spring Security configuration:
`@override
protected void configure(HttpSecurity http) throws Exception {// @Formatter:off
http
.authorizeRequests()
.antMatchers("/js/", "/fonts/", "/css/", "/images/", "/favicon.ico").permitAll()
.antMatchers("/register/").permitAll()
// .antMatchers("/login/").permitAll()//Basically I'm allowing parameters for login so locale can be added and read.
.anyRequest().authenticated();
enhancer.addRecaptchaSupport(http.formLogin())
.loginPage("/login")
.successHandler(myUrlAuthenticationSuccessHandler)
.permitAll()
.and()
.csrf()
.disable()
.logout().logoutRequestMatcher(new AntPathRequestMatcher("/logout"))
.logoutSuccessUrl("/login")
.invalidateHttpSession(true)
.permitAll();

}`

**Comment by mkopylec** [comment]
By default the captcha widget is shown after 5 unsuccessful login tries **for the same username**.
If you want to change the treshold you can do it by setting: `recaptcha.security.loginFailuresThreshold` in application.yml file.

**Comment by mkopylec** [comment]
https://github.com/mkopylec/recaptcha-spring-boot-starter#configuration-properties-list

**Comment by manojsharma20** [comment]
Thanks, i was not aware of that.

**Comment by mkopylec** [comment]
Is the issue solved? If so, please close it.

**Comment by mkopylec** [comment]
I'm closing the issue. Please re-open it if you need more help.
